### ISSUE TITLE
M3FD数据集划分好的训练集和验证集能上传百度网盘吗，谷歌打不开

### ISSUE THREAD

**Issue by leileilei2000** [FreeformRobotics/EAEFNet#16]

**Comment by qiherong** [comment]
请问下这个划分的链接在哪里？
数据集解压出来没有划分

**Comment by leileilei2000** [comment]
> 请问下这个划分的链接在哪里？ 数据集解压出来没有划分

就在这个EAEFNet主页下面的链接里啊，有一个M3FD的数据集谷歌云盘链接，但是我访问不了，所以想要一个百度网盘链接

**Comment by duoxiangqinzuo** [comment]
> > 请问下这个划分的链接在哪里？ 数据集解压出来没有划分
> 
> 就在这个EAEFNet主页下面的链接里啊，有一个M3FD的数据集谷歌云盘链接，但是我访问不了，所以想要一个百度网盘链接

https://github.com/dlut-dimt/TarDAL
这个数据集的链接就是源自这个，里面有百度网盘的下载链接，但是没有划分方式。
如果你找到了划分方式，希望能够和我分享。

**Comment by matrixgame2018** [comment]
![1728613025276](https://github.com/user-attachments/assets/7eb6146c-7d4f-48f9-b185-82ae7f268ce6)

**Comment by duoxiangqinzuo** [comment]
> ![1728613025276](https://private-user-images.githubusercontent.com/45811724/375603358-7eb6146c-7d4f-48f9-b185-82ae7f268ce6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzA1MzgsIm5iZiI6MTcyODYzMDIzOCwicGF0aCI6Ii80NTgxMTcyNC8zNzU2MDMzNTgtN2ViNjE0NmMtN2Q0Zi00OGY5LWIxODUtODJhZTdmMjY4Y2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA3MDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ODY1ZGZmYjAwOGIyNzI5OTIwYjgwZDYwMjVhMjAyYzgyODAxZGU1ZThjZTkyNjVmYTdlMDk4MDc4MWRjMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5ezFJVaFUwDXaTS3A6QMMqUTJOlQYhpYkj_4AHvSnDo)

非常感谢您的回复！是我眼拙了，没有看到这行小字。祝您一切顺利！

**Comment by leileilei2000** [comment]
> > ![1728613025276](https://private-user-images.githubusercontent.com/45811724/375603358-7eb6146c-7d4f-48f9-b185-82ae7f268ce6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzA1MzgsIm5iZiI6MTcyODYzMDIzOCwicGF0aCI6Ii80NTgxMTcyNC8zNzU2MDMzNTgtN2ViNjE0NmMtN2Q0Zi00OGY5LWIxODUtODJhZTdmMjY4Y2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA3MDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ODY1ZGZmYjAwOGIyNzI5OTIwYjgwZDYwMjVhMjAyYzgyODAxZGU1ZThjZTkyNjVmYTdlMDk4MDc4MWRjMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5ezFJVaFUwDXaTS3A6QMMqUTJOlQYhpYkj_4AHvSnDo)
> 
> 非常感谢您的回复！是我眼拙了，没有看到这行小字。祝您一切顺利！

如果你可以下载谷歌云盘，请问是否可以把下载好的M3FD数据集分享到我的邮箱呢，十分感谢！我的邮箱是2303025778@qq.com

**Comment by duoxiangqinzuo** [comment]
> > > ![1728613025276](https://private-user-images.githubusercontent.com/45811724/375603358-7eb6146c-7d4f-48f9-b185-82ae7f268ce6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzA1MzgsIm5iZiI6MTcyODYzMDIzOCwicGF0aCI6Ii80NTgxMTcyNC8zNzU2MDMzNTgtN2ViNjE0NmMtN2Q0Zi00OGY5LWIxODUtODJhZTdmMjY4Y2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA3MDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ODY1ZGZmYjAwOGIyNzI5OTIwYjgwZDYwMjVhMjAyYzgyODAxZGU1ZThjZTkyNjVmYTdlMDk4MDc4MWRjMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5ezFJVaFUwDXaTS3A6QMMqUTJOlQYhpYkj_4AHvSnDo)
> > 
> > 
> > 非常感谢您的回复！是我眼拙了，没有看到这行小字。祝您一切顺利！
> 
> 如果你可以下载谷歌云盘，请问是否可以把下载好的M3FD数据集分享到我的邮箱呢，十分感谢！我的邮箱是[2303025778@qq.com](mailto:2303025778@qq.com)

数据太大了，建议你先去原链接下载数据，我可以将作者的划分方式分享给你

**Comment by duoxiangqinzuo** [comment]
> > > ![1728613025276](https://private-user-images.githubusercontent.com/45811724/375603358-7eb6146c-7d4f-48f9-b185-82ae7f268ce6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzA1MzgsIm5iZiI6MTcyODYzMDIzOCwicGF0aCI6Ii80NTgxMTcyNC8zNzU2MDMzNTgtN2ViNjE0NmMtN2Q0Zi00OGY5LWIxODUtODJhZTdmMjY4Y2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA3MDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ODY1ZGZmYjAwOGIyNzI5OTIwYjgwZDYwMjVhMjAyYzgyODAxZGU1ZThjZTkyNjVmYTdlMDk4MDc4MWRjMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5ezFJVaFUwDXaTS3A6QMMqUTJOlQYhpYkj_4AHvSnDo)
> > 
> > 
> > 非常感谢您的回复！是我眼拙了，没有看到这行小字。祝您一切顺利！
> 
> 如果你可以下载谷歌云盘，请问是否可以把下载好的M3FD数据集分享到我的邮箱呢，十分感谢！我的邮箱是[2303025778@qq.com](mailto:2303025778@qq.com)

数据太大了，我还在下，建议你去TarDAL下载，如果我下载成功了，可以将作者的划分方式分享给你。

**Comment by ironmanfcf** [comment]
> > > > ![1728613025276](https://private-user-images.githubusercontent.com/45811724/375603358-7eb6146c-7d4f-48f9-b185-82ae7f268ce6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzA1MzgsIm5iZiI6MTcyODYzMDIzOCwicGF0aCI6Ii80NTgxMTcyNC8zNzU2MDMzNTgtN2ViNjE0NmMtN2Q0Zi00OGY5LWIxODUtODJhZTdmMjY4Y2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA3MDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ODY1ZGZmYjAwOGIyNzI5OTIwYjgwZDYwMjVhMjAyYzgyODAxZGU1ZThjZTkyNjVmYTdlMDk4MDc4MWRjMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5ezFJVaFUwDXaTS3A6QMMqUTJOlQYhpYkj_4AHvSnDo)
> > > 
> > > 
> > > 非常感谢您的回复！是我眼拙了，没有看到这行小字。祝您一切顺利！
> > 
> > 
> > 如果你可以下载谷歌云盘，请问是否可以把下载好的M3FD数据集分享到我的邮箱呢，十分感谢！我的邮箱是[2303025778@qq.com](mailto:2303025778@qq.com)
> 
> 数据太大了，我还在下，建议你去TarDAL下载，如果我下载成功了，可以将作者的划分方式分享给你。

你好，能发我一下作者的划分方式吗，我的邮箱是2399642395@qq.com
