### ISSUE TITLE
请问M3FD数据集的划分方式是什么

### ISSUE THREAD

**Issue by duoxiangqinzuo** [FreeformRobotics/EAEFNet#17]
您好，很多未开源的论文都声称是按照您的划分方式进行比较，可是我在代码中并没有找到划分数据集的部分。
请问您可以指出数据集的划分方式吗？

**Comment by matrixgame2018** [comment]
另外，我并不支持您去使用这个数据集的划分方案，因为这毕竟是两年前的工作。您可以去联系TarDAL的作者，他们对于这个部分有全新的补充。最后，感谢您对于我工作的关注。


2443434059
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FreeformRobotics/EAEFNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月11日(星期五) 上午10:11
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[FreeformRobotics/EAEFNet] M3FD数据集划分 (Issue #17)





 
您好，很多论文都声称是按照您的划分方式进行比较，可是我在代码中并没有找到划分数据集的部分。请问您可以指出吗？
