### ISSUE TITLE
is weight file right or not？

### ISSUE THREAD

**Issue by rRaphae1** [FreeformRobotics/EAEFNet#3]
I pull the code and download the weight from Google driver, modify the dataset path, and then run 'python test.py' in 'EAEFNET_SOD' directory. But there are errors like these:   
![image](https://github.com/FreeformRobotics/EAEFNet/assets/49720512/59f739eb-c8f1-4f18-9dc3-a5dd49aaece1)
So, I find the 'mlp_pool' and the code is like this:
![image](https://github.com/FreeformRobotics/EAEFNet/assets/49720512/66e53558-5093-459e-84f0-938d3452b781)
obviously, according to the error, the code should be like this:
![image](https://github.com/FreeformRobotics/EAEFNet/assets/49720512/888f8308-81fb-4ff1-8e5a-15dd353c0f0f)
and the code can running correctly, but the results are too bad, 
![image](https://github.com/FreeformRobotics/EAEFNet/assets/49720512/52f0b3b8-1120-412f-9ce6-7e568e809289)
so, can you tell me where the mistakes are?!!!

**Comment by matrixgame2018** [comment]
Thank you very much for your report, your understanding is correct, there are some mistakes in the EAEF_50weights, we will update the weights file later
