### ISSUE TITLE
Detection dataset setting issue

### ISSUE THREAD

**Issue by yumi312** [FreeformRobotics/EAEFNet#4]
hello, I want to try the Detection model while using M3FD dataset but when I am trying script "tools/test.py", there comes the error ``mean` should have 1 or 3 values, to be compatible with RGB or gray image, but got 4 values`.
I don't know how to set the dataset properly, I just followed the guide `python EAEF_mmyolo/tools/test.py yolov5/bi_yolov5 `.
I'm a learner about this subject. Thanks for your helping.

**Comment by matrixgame2018** [comment]
Maybe you can download preprocessing M3FD from [Pre-M3FD](https://drive.google.com/drive/folders/1fqNwaumH0BrcAIvS0ebAjS35LX31Yw4S)， or whether you should concatenate the RGB and Thermal Image to get a 4-channel image before the model testing

**Comment by yumi312** [comment]
where should I put those dataset?

**Comment by matrixgame2018** [comment]
There are no special rules for the path of those datasets.

**Comment by yumi312** [comment]
The first question i met when i set the environment was this one.
> # Install MMYOLO , don't forget it!
> mim install -v -e .

I met the error
> ModuleNotFoundError: No module named 'torch'
>   error: subprocess-exited-with-error

I searched the official doc from mmlab, I found they said u can try `min install "mmyolo"`. I tried this method and i think the installation successed.

Then I tried to run `python EAEF_mmyolo/tools/test.py yolov5/bi_yolov5` it happened some path issue and I solved it. The program ran but the error message showed: `mean should have 1 or 3 values, to be compatible with RGB or gray image, but got 4 values`

**Comment by matrixgame2018** [comment]
You should install the mmyolo in develop-mode not run-mode, so  please follow the  https://github.com/open-mmlab/mmyolo/blob/main/docs/en/get_started/installation.md
```
Step 1. Install MMYOLO.

Case a: If you develop and run mmdet directly, install it from source:

git clone https://github.com/open-mmlab/mmyolo.git
cd mmyolo
# Install albumentations
pip install -r requirements/albu.txt
# Install MMYOLO
mim install -v -e .
# "-v" means verbose, or more output
# "-e" means installing a project in editable mode,
# thus any local modifications made to the code will take effect without reinstallation.
```
