### ISSUE TITLE
Why have the training data already been fused with RGB and thermal images?

### ISSUE THREAD

**Issue by yumi312** [FreeformRobotics/EAEFNet#5]
Hello, I downloaded your dataset from Google Drive, and I noticed that these images appear to be fused. 
I'm curious about the method you used to fuse these two modalities, as described in your paper

**Comment by matrixgame2018** [comment]
As I said before, RGB(3 channels) and Thermal(1 channel) are stitched into a 4-channel image (RGBT), which I have provided on Google Drive.

**Comment by yumi312** [comment]
I noticed that you provided a folder called M3FD_Fusion, which contains IR and VIS images. I believe you might have used a method to fuse these images, as described in your paper. This part is particularly intriguing.

**Comment by matrixgame2018** [comment]
You should not have a deep understanding of the logic of my work and some other content in related fields. 
What I need to emphasize to you again is that, first of all, the images I provide are 4-channel and the image after M3FD fusion is 3-channel. Secondly, you can check the model structure part of mmyolo. It can be found that this is a Yolov5_m network that supports 3+1 input.
