### ISSUE TITLE
Asking for help about FuseSeg and visualization of attention maps

### ISSUE THREAD

**Issue by wdhudiekou** [FreeformRobotics/EAEFNet#6]
Excuse me. I can't find the code of FuseSeg, could you please provide it to me?

**Comment by matrixgame2018** [comment]
It is a pity that as far as I know, the author has no intention of making the code public. If you are interested in its reproduction, welcome to discuss it with me.

**Comment by matrixgame2018** [comment]
Thank you for your interest in the EAEFNet work. To implement CAM in EAEFNet, I modified the Grad-CAM code to adapt it to the structure of dual-stream input. This may be why you are unable to reproduce successfully. Additionally, I will open source the visualization code this week.

**Comment by matrixgame2018** [comment]
Hello, I have updated the cam visualization code in [CAM Reference](https://github.com/matrixgame2018/FEANet/tree/main/project), but this is just a toy demo and not a full-blown project. If you have any questions please contact me.

**Comment by seenthestars** [comment]
Excuse me. I'm very interested in this article called EAEFNet and read it several times. I have one more question to ask you.There are still many doubts about whether the figures and formulas in the paper are correct when understanding the formula given in the paper based on Figure 3.

**Comment by matrixgame2018** [comment]
If you want me to explain Figure 3 to you in more detail, you can find me through email at 2443434059@qq.com. If you have WeChat, you can find me through mz18026806328. 

Thanks
