### ISSUE TITLE
Regarding the mIoU value on MFN Dataset

### ISSUE THREAD

**Issue by yuwenmichael** [FreeformRobotics/EAEFNet#7]
I trained for 100 epoch with everything as the default values but only got a mIoU of around 57.1. There is a huge gap between the paper (58.9) and the result that I am having. Is there any reason for this?

**Comment by matrixgame2018** [comment]
I think this issuse can give you some advice [https://github.com/FreeformRobotics/EAEFNet/issues/2](url)
